# Generated by Django 4.2.6 on 2023-11-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('mobile', models.PositiveIntegerField(max_length=10)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
