# Generated by Django 4.2.6 on 2023-11-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('mobile', models.PositiveIntegerField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
