# Generated by Django 4.2.6 on 2023-11-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_seller_company_alter_profile_pincode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_details',
        ),
    ]
