# Generated by Django 4.2.6 on 2023-11-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_seller_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='company',
        ),
    ]
