# Generated by Django 4.2.6 on 2023-11-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_seller_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
