# Generated by Django 4.2.6 on 2023-11-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
