# Generated by Django 4.2.6 on 2023-11-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('company', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('mobile', models.PositiveIntegerField(unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
