# Generated by Django 4.2.6 on 2023-11-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_2',
            field=models.ImageField(default=None, upload_to='product_name'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_3',
            field=models.ImageField(default=None, upload_to='product_name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=None, upload_to='product_name'),
        ),
    ]
