# Generated by Django 4.2.6 on 2023-11-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_product_product_image_2_product_product_image_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=True, upload_to='product_name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_2',
            field=models.ImageField(default=True, upload_to='product_name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_3',
            field=models.ImageField(default=True, upload_to='product_name'),
        ),
    ]
