# Generated by Django 4.2.6 on 2023-11-27 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_product_product_image_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image_3',
        ),
    ]
